title: kushwanthreddy blog

description: Kushwanth Reddy Blog

baseurl: "https://blog.kushwanthreddy.com"

permalink: /:title/

sass:
  style: :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .well-known/
  - .well-known/assetlinks.json

include:
  - ...
  - _redirects
