title: kushwanthreddy blog

description: Kushwanth Reddy Blog

baseurl: "https://blog.kushwanthreddy.com"

permalink: /:title/

sass:
  style: :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
exclude: ['.well-known/assetlinks.json' ,'.well-known']
